version: '3.8'

services:


  postgres:
    image: postgres:15-alpine
    container_name: kajix_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kajix
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./reset.sql:/docker-entrypoint-initdb.d/reset.sql

  postgres_test:
    image: postgres:15-alpine
    container_name: kajix_postgres_test
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kajix_test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./reset.sql:/docker-entrypoint-initdb.d/reset.sql

volumes:
  postgres_data:
  postgres_test_data:
