#!/usr/bin/env bash

echo "Running type checking..."
npm run type-check

echo "Running backend verification..."
npm run build:api && npm run test:api:e2e

echo "Running frontend verification..."
npm run lint:ui && npm run build:ui
