name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: "20.x"
  NODE_ENV: "test"

jobs:
  test-api:
    name: Test API
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: kajix-api/package-lock.json

      - name: Install API Dependencies
        working-directory: ./kajix-api
        run: npm ci

      - name: Run API Tests
        working-directory: ./kajix-api
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          NODE_ENV: ${{ env.NODE_ENV }}
        run: |
          npm run test:db:migrate
          npm run test
          npm run test:e2e -- --forceExit

  test-ui:
    name: Test UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: kajix-ui/package-lock.json

      - name: Install UI Dependencies
        working-directory: ./kajix-ui
        run: npm ci

      - name: Run UI Linting
        working-directory: ./kajix-ui
        run: npm run lint

      - name: Build UI
        working-directory: ./kajix-ui
        run: npm run build

  deploy-api:
    name: Deploy API
    needs: [test-api]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: kajix-api/package-lock.json

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy API to Vercel
        working-directory: ./kajix-api
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_API_PROJECT_ID }}
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  deploy-ui:
    name: Deploy UI
    needs: [test-ui]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: kajix-ui/package-lock.json

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy UI to Vercel
        working-directory: ./kajix-ui
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_UI_PROJECT_ID }}
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
